// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: example.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "rpx";

export interface PingRequest {
  value: string;
}

export interface PingResponse {
  Value: string;
}

function createBasePingRequest(): PingRequest {
  return { value: "" };
}

export const PingRequest = {
  encode(message: PingRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingRequest {
    return { value: isSet(object.value) ? globalThis.String(object.value) : "" };
  },

  toJSON(message: PingRequest): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingRequest>, I>>(base?: I): PingRequest {
    return PingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingRequest>, I>>(object: I): PingRequest {
    const message = createBasePingRequest();
    message.value = object.value ?? "";
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { Value: "" };
}

export const PingResponse = {
  encode(message: PingResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Value !== "") {
      writer.uint32(10).string(message.Value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingResponse {
    return { Value: isSet(object.Value) ? globalThis.String(object.Value) : "" };
  },

  toJSON(message: PingResponse): unknown {
    const obj: any = {};
    if (message.Value !== "") {
      obj.Value = message.Value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingResponse>, I>>(base?: I): PingResponse {
    return PingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingResponse>, I>>(object: I): PingResponse {
    const message = createBasePingResponse();
    message.Value = object.Value ?? "";
    return message;
  },
};

export interface TestService {
  PingEmpty(request: Empty): Promise<PingResponse>;
  Ping(request: PingRequest): Promise<PingResponse>;
  PingError(request: PingRequest): Promise<Empty>;
  PingList(request: PingRequest): Observable<PingResponse>;
  PingPongBidi(request: Observable<PingRequest>): Observable<PingResponse>;
  PingStream(request: Observable<PingRequest>): Promise<PingResponse>;
}

export const TestServiceServiceName = "rpx.TestService";
export class TestServiceClientImpl implements TestService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TestServiceServiceName;
    this.rpc = rpc;
    this.PingEmpty = this.PingEmpty.bind(this);
    this.Ping = this.Ping.bind(this);
    this.PingError = this.PingError.bind(this);
    this.PingList = this.PingList.bind(this);
    this.PingPongBidi = this.PingPongBidi.bind(this);
    this.PingStream = this.PingStream.bind(this);
  }
  PingEmpty(request: Empty): Promise<PingResponse> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "PingEmpty", data);
    return promise.then((data) => PingResponse.decode(_m0.Reader.create(data)));
  }

  Ping(request: PingRequest): Promise<PingResponse> {
    const data = PingRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Ping", data);
    return promise.then((data) => PingResponse.decode(_m0.Reader.create(data)));
  }

  PingError(request: PingRequest): Promise<Empty> {
    const data = PingRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PingError", data);
    return promise.then((data) => Empty.decode(_m0.Reader.create(data)));
  }

  PingList(request: PingRequest): Observable<PingResponse> {
    const data = PingRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "PingList", data);
    return result.pipe(map((data) => PingResponse.decode(_m0.Reader.create(data))));
  }

  PingPongBidi(request: Observable<PingRequest>): Observable<PingResponse> {
    const data = request.pipe(map((request) => PingRequest.encode(request).finish()));
    const result = this.rpc.bidirectionalStreamingRequest(this.service, "PingPongBidi", data);
    return result.pipe(map((data) => PingResponse.decode(_m0.Reader.create(data))));
  }

  PingStream(request: Observable<PingRequest>): Promise<PingResponse> {
    const data = request.pipe(map((request) => PingRequest.encode(request).finish()));
    const promise = this.rpc.clientStreamingRequest(this.service, "PingStream", data);
    return promise.then((data) => PingResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
